### PR TITLE
Leave out local packages from synchronization

### PR DESCRIPTION
**Pull request by RolKau**
If the version starts with the url scheme 'file:' that means that the package is fetched from the local filesystem relative to the package-lock that we were passed; it could for instance be a git submodule. This package will not be fetched through the web server that we set up anyway, so don't attempt to synchronize it.

### CODE REVIEW

**Comment by heikkipora** [comment]
Please do `npm run eslint:check` on your PR branch and fix the reported (trivial) issues. Otherwise looks good 👍

**Comment by RolKau** [comment]
Sorry about that; for some reason I had convinced myself that this was part of the commit-hook. Anyway, it should be fixed now.

**Comment by RolKau** [comment]
Squashed the change into the main patch, to unclutter the history.

**Comment by heikkipora** [comment]
Thanks!

**Comment by heikkipora** [comment]
Released as part of https://github.com/heikkipora/registry-sync/releases/tag/v3.3.0

**Pull request merged**
